Import important libraries 

In [59]:
import pandas as pd
import numpy as np

Using chardet library to know the exact encoding type for the CSV file


In [60]:
import chardet
with open('globalterrorismdb_0718dist.csv','rb') as obj:
    result=chardet.detect(obj.read(20000))
print(result)

{'encoding': 'ISO-8859-1', 'confidence': 0.73, 'language': ''}


Reading CSV file

In [61]:
df=pd.read_csv('globalterrorismdb_0718dist.csv',encoding='ISO-8859-1')
pd.set_option('display.max_columns', None)
df.head(10)

C:\Users\KimoStore\AppData\Local\Temp\ipykernel_4476\1206452247.py:1: DtypeWarning:

Columns (4,6,31,33,61,62,63,76,79,90,92,94,96,114,115,121) have mixed types. Specify dtype option on import or set low_memory=False.



eventid  iyear  imonth  iday approxdate  extended resolution  country  \
0  197000000001   1970       7     2        NaN         0        NaN       58   
1  197000000002   1970       0     0        NaN         0        NaN      130   
2  197001000001   1970       1     0        NaN         0        NaN      160   
3  197001000002   1970       1     0        NaN         0        NaN       78   
4  197001000003   1970       1     0        NaN         0        NaN      101   
5  197001010002   1970       1     1        NaN         0        NaN      217   
6  197001020001   1970       1     2        NaN         0        NaN      218   
7  197001020002   1970       1     2        NaN         0        NaN      217   
8  197001020003   1970       1     2        NaN         0        NaN      217   
9  197001030001   1970       1     3        NaN         0        NaN      217   

          country_txt  region                   region_txt   provstate  \
0  Dominican Republic       2  Central America & Caribbean         NaN   
1              Mexico       1                North America     Federal   
2         Philippines       5               Southeast Asia      Tarlac   
3              Greece       8               Western Europe      Attica   
4               Japan       4                    East Asia     Fukouka   
5       United States       1                North America    Illinois   
6             Uruguay       3                South America  Montevideo   
7       United States       1                North America  California   
8       United States       1                North America   Wisconsin   
9       United States       1                North America   Wisconsin   

            city   latitude   longitude  specificity  vicinity  \
0  Santo Domingo  18.456792  -69.951164          1.0         0   
1    Mexico city  19.371887  -99.086624          1.0         0   
2        Unknown  15.478598  120.599741          4.0         0   
3         Athens  37.997490   23.762728          1.0         0   
4        Fukouka  33.580412  130.396361          1.0         0   
5          Cairo  37.005105  -89.176269          1.0         0   
6     Montevideo -34.891151  -56.187214          1.0         0   
7        Oakland  37.791927 -122.225906          1.0         0   
8        Madison  43.076592  -89.412488          1.0         0   
9        Madison  43.072950  -89.386694          1.0         0   

          location                                            summary  crit1  \
0              NaN                                                NaN      1   
1              NaN                                                NaN      1   
2              NaN                                                NaN      1   
3              NaN                                                NaN      1   
4              NaN                                                NaN      1   
5              NaN  1/1/1970: Unknown African American assailants ...      1   
6              NaN                                                NaN      1   
7  Edes Substation  1/2/1970: Unknown perpetrators detonated explo...      1   
8              NaN  1/2/1970: Karl Armstrong, a member of the New ...      1   
9              NaN  1/3/1970: Karl Armstrong, a member of the New ...      1   

   crit2  crit3  doubtterr  alternative   alternative_txt  multiple  success  \
0      1      1        0.0          NaN               NaN       0.0        1   
1      1      1        0.0          NaN               NaN       0.0        1   
2      1      1        0.0          NaN               NaN       0.0        1   
3      1      1        0.0          NaN               NaN       0.0        1   
4      1      1       -9.0          NaN               NaN       0.0        1   
5      1      1        0.0          NaN               NaN       0.0        1   
6      1      1        0.0          NaN               NaN       0.0        0   
7      1      1        1.0          2.0  Other Crime 

In [62]:
df.info(verbose = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181691 entries, 0 to 181690
Data columns (total 135 columns):
 #    Column              Dtype  
---   ------              -----  
 0    eventid             int64  
 1    iyear               int64  
 2    imonth              int64  
 3    iday                int64  
 4    approxdate          object 
 5    extended            int64  
 6    resolution          object 
 7    country             int64  
 8    country_txt         object 
 9    region              int64  
 10   region_txt          object 
 11   provstate           object 
 12   city                object 
 13   latitude            float64
 14   longitude           float64
 15   specificity         float64
 16   vicinity            int64  
 17   location            object 
 18   summary             object 
 19   crit1               int64  
 20   crit2               int64  
 21   crit3               int64  
 22   doubtterr           float64
 23   alternative         float64
 24 

In [63]:
df[df.duplicated()]

Empty DataFrame
Columns: [eventid, iyear, imonth, iday, approxdate, extended, resolution, country, country_txt, region, region_txt, provstate, city, latitude, longitude, specificity, vicinity, location, summary, crit1, crit2, crit3, doubtterr, alternative, alternative_txt, multiple, success, suicide, attacktype1, attacktype1_txt, attacktype2, attacktype2_txt, attacktype3, attacktype3_txt, targtype1, targtype1_txt, targsubtype1, targsubtype1_txt, corp1, target1, natlty1, natlty1_txt, targtype2, targtype2_txt, targsubtype2, targsubtype2_txt, corp2, target2, natlty2, natlty2_txt, targtype3, targtype3_txt, targsubtype3, targsubtype3_txt, corp3, target3, natlty3, natlty3_txt, gname, gsubname, gname2, gsubname2, gname3, gsubname3, motive, guncertain1, guncertain2, guncertain3, individual, nperps, nperpcap, claimed, claimmode, claimmode_txt, claim2, claimmode2, claimmode2_txt, claim3, claimmode3, claimmode3_txt, compclaim, weaptype1, weaptype1_txt, weapsubtype1, weapsubtype1_txt, weaptype2, weaptype2_txt, weapsubtype2, weapsubtype2_txt, weaptype3, weaptype3_txt, weapsubtype3, weapsubtype3_txt, weaptype4, weaptype4_txt, weapsubtype4, weapsubtype4_txt, weapdetail, nkill, nkillus, ...]
Index: []

In [64]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
missing_values_percentage = (df.isnull().sum() / len(df)) * 100
missing_values_df = missing_values_percentage.reset_index()
missing_values_df.columns = ['Column', 'Missing Percentage']

print(missing_values_df)

                 Column  Missing Percentage
0               eventid            0.000000
1                 iyear            0.000000
2                imonth            0.000000
3                  iday            0.000000
4            approxdate           94.914993
5              extended            0.000000
6            resolution           98.778145
7               country            0.000000
8           country_txt            0.000000
9                region            0.000000
10           region_txt            0.000000
11            provstate            0.231712
12                 city            0.239417
13             latitude            2.507554
14            longitude            2.508104
15          specificity            0.003302
16             vicinity            0.000000
17             location           69.456385
18              summary           36.396409
19                crit1            0.000000
20                crit2            0.000000
21                crit3         

In [65]:
cleaned_df=df[['eventid', 'iyear', 'imonth', 'iday', 'extended', 'country',
       'country_txt', 'region', 'region_txt', 'provstate', 'city', 'latitude',
       'longitude', 'specificity', 'vicinity', 'summary', 'crit1',
       'crit2', 'crit3', 'doubtterr', 'multiple', 'success', 'suicide',
       'attacktype1', 'attacktype1_txt', 'targtype1', 'targtype1_txt',
       'targsubtype1', 'targsubtype1_txt', 'corp1', 'target1', 'natlty1',
       'natlty1_txt', 'gname', 'motive', 'guncertain1', 'individual', 'nperps',
       'nperpcap', 'claimed', 'weaptype1', 'weaptype1_txt', 'weapsubtype1',
       'weapsubtype1_txt', 'weapdetail', 'nkill', 'nkillus', 'nkillter',
       'nwound', 'nwoundus', 'nwoundte', 'property', 'propextent',
       'propextent_txt', 'propcomment', 'ishostkid', 'ransom',
       'scite1', 'scite2','dbsource', 'INT_LOG', 'INT_IDEO',
       'INT_MISC', 'INT_ANY']]

In [66]:
cleaned_df.rename(columns =
                    {'iyear':'year', 
                   'imonth':'month',
                   'iday':'day',
                   'country':'country_code',
                   'country_txt' : 'country',
                   'region': 'regioncode',
                   'region_txt' : 'region',
                   'crit1' : 'crit',
                   'attacktype1_txt' : 'attack_type',
                   'targtype1_txt' : 'target_type',
                   'targsubtype1_txt': 'target_subtype',
                   'crop1':'targetName',
                   'natlty1_txt' : 'nationality_of_victom',
                   'gname' : 'organisation',
                   'claimed' : 'claime_dresp',
                   'weaptype1_txt' : 'weapon_type',
                   'nkill' : 'num_killed',
                   'nkillter' : 'num_terrorist_killed',
                   'nwound' : 'num_wounded',
                   'nwoundte':'num_terrorist_wounded',
                   'propextent_txt' : 'propextent_desc',
                   'ransom' : 'ransom_demanded',}, inplace = True)

C:\Users\KimoStore\AppData\Local\Temp\ipykernel_4476\1538154914.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [67]:
cleaned_df.describe()

eventid           year          month            day  \
count  1.816910e+05  181691.000000  181691.000000  181691.000000   
mean   2.002705e+11    2002.638997       6.467277      15.505644   
std    1.325957e+09      13.259430       3.388303       8.814045   
min    1.970000e+11    1970.000000       0.000000       0.000000   
25%    1.991021e+11    1991.000000       4.000000       8.000000   
50%    2.009022e+11    2009.000000       6.000000      15.000000   
75%    2.014081e+11    2014.000000       9.000000      23.000000   
max    2.017123e+11    2017.000000      12.000000      31.000000   

            extended   country_code     regioncode       latitude  \
count  181691.000000  181691.000000  181691.000000  177135.000000   
mean        0.045346     131.968501       7.160938      23.498343   
std         0.208063     112.414535       2.933408      18.569242   
min         0.000000       4.000000       1.000000     -53.154613   
25%         0.000000      78.000000       5.000000      11.510046   
50%         0.000000      98.000000       6.000000      31.467463   
75%         0.000000     160.000000      10.000000      34.685087   
max         1.000000    1004.000000      12.000000      74.633553   

          longitude    specificity       vicinity           crit  \
count  1.771340e+05  181685.000000  181691.000000  181691.000000   
mean  -4.586957e+02       1.451452       0.068297       0.988530   
std    2.047790e+05       0.995430       0.284553       0.106483   
min   -8.618590e+07       1.000000      -9.000000       0.000000   
25%    4.545640e+00       1.000000       0.000000       1.000000   
50%    4.324651e+01       1.000000       0.000000       1.000000   
75%    6.871033e+01       1.000000       0.000000       1.000000   
max    1.793667e+02       5.000000       1.000000       1.000000   

               crit2          crit3      doubtterr       multiple  \
count  181691.000000  181691.000000  181690.000000  181690.000000   
mean        0.993093       0.875668      -0.523171       0.137773   
std         0.082823       0.329961       2.455819       0.344663   
min         0.000000       0.000000      -9.000000       0.000000   
25%         1.000000       1.000000       0.000000       0.000000   
50%         1.000000       1.000000       0.000000       0.000000   
75%         1.000000       1.000000       0.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

             success        suicide    attacktype1      targtype1  \
count  181691.000000  181691.000000  181691.000000  181691.000000   
mean        0.889598       0.036507       3.247547       8.439719   
std         0.313391       0.187549       1.915772       6.653838   
min         0.000000       0.000000       1.000000       1.000000   
25%         1.000000       0.000000       2.000000       3.000000   
50%         1.000000       0.000000       3.000000       4.000000   
75%         1.000000       0.000000       3.000000      14.000000   
max         1.000000       1.000000       9.000000      22.000000   

        targsubtype1        natlty1    guncertain1     individual  \
count  171318.000000  180132.000000  181311.000000  181691.000000   
mean       46.971474     127.686441       0.081440       0.002950   
std        30.953357      89.299120       0.273511       0.054234   
min         1.000000       4.000000       0.000000       0.000000   
25%        22.000000      83.000000       0.000000       0.000000   
50%        35.000000     101.000000       0.000000       0.000000   
75%        74.000000     173.000000       0.000000       0.000000   
max       113.000000    1004.000000       1.000000       1.000000   

              nperps       nperpcap   claime_dresp      weaptype1  \
count  110576.000000  112202.000000  115571.000000  181691.000000   
mean      -65.361154      -1.517727       0.049666       6.447325   
std       216.536633      12.830346       1.093195       2.173435   
min       -99.000000  

Check validity of columns: Numerical first

In [68]:
cleaned_df['vicinity'].unique()

array([ 0,  1, -9])

In [69]:
cleaned_df[cleaned_df['vicinity']<0].shape[0]

35

In [70]:
cleaned_df['vicinity'] = cleaned_df['vicinity'].replace(-9, 0)

C:\Users\KimoStore\AppData\Local\Temp\ipykernel_4476\500978241.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [71]:
cleaned_df['doubtterr'].unique()

array([ 0., -9.,  1., nan])

In [72]:
cleaned_df[cleaned_df['doubtterr']<0].shape[0]

13784

In [73]:
cleaned_df['doubtterr'] = cleaned_df['doubtterr'].replace(-9, 0)

C:\Users\KimoStore\AppData\Local\Temp\ipykernel_4476\696071356.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [74]:
cleaned_df['nperps'].unique()

array([      nan,  7.00e+00, -9.90e+01,  3.00e+00,  1.00e+00,  5.00e+00,
        2.00e+00,  4.00e+00,  6.00e+00,  4.20e+01,  2.20e+01,  9.00e+00,
        2.50e+01,  1.60e+01,  1.10e+01,  1.20e+01,  8.00e+00,  0.00e+00,
        1.50e+01,  1.00e+01,  1.80e+01,  1.70e+01,  2.00e+02,  3.00e+01,
        6.00e+01,  2.00e+01,  5.00e+01,  1.30e+01,  2.40e+01,  7.00e+01,
        4.00e+01,  1.00e+02,  1.40e+01,  1.40e+02,  8.00e+01,  3.20e+01,
        4.00e+02,  1.00e+03,  2.50e+02,  3.50e+01,  1.50e+02,  3.00e+02,
        7.50e+01,  5.00e+02,  6.00e+02,  4.40e+01,  4.50e+01,  3.80e+01,
        9.00e+01,  1.20e+02,  3.40e+01,  2.70e+01,  1.80e+02,  9.00e+02,
        1.20e+03,  3.70e+02,  1.30e+02,  7.50e+02,  4.80e+01,  7.00e+02,
        7.20e+01,  3.30e+01,  3.90e+01,  4.90e+01,  2.60e+01,  1.90e+01,
        2.90e+02,  6.80e+01,  1.60e+02,  2.04e+02,  2.80e+01,  3.60e+01,
        2.10e+01,  2.50e+04,  2.90e+01,  1.50e+03,  2.50e+03,  1.90e+02,
        4.70e+01,  1.00e+04,  1.38e+02,  2.00e+04, 

In [75]:
cleaned_df[cleaned_df['nperps']<0].shape[0]

82220

In [76]:
cleaned_df['nperps'] = cleaned_df['nperps'].replace(-9, 0)

C:\Users\KimoStore\AppData\Local\Temp\ipykernel_4476\3356706360.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [77]:
cleaned_df['nperpcap'].unique()

array([  nan, -99. ,   1. ,   2. ,   0. ,   4. ,   3. ,   6. ,   5. ,
         7. ,   8. ,   9. ,  10. ,  26. ,  24. ,  13. ,  14. ,  45. ,
        12. ,  11. ,   2.5,  25. ,  32. ,  27. ,  -9. ,  15. ,  43. ,
        21. ,  50. , 406. ,  17. , 100. ,  60. ,  87. ,  55. ,  20. ,
        18. ,  76. ,  29. ,  40. , 271. ,  28. ,  16. ,  19. ,  30. ,
       200. ,  41. , 126. ,  23. ,  22. ,  63. ])

In [78]:
cleaned_df[cleaned_df['nperpcap']<0].shape[0]

1866

In [79]:
cleaned_df['nperpcap'] = cleaned_df['nperpcap'].replace(-9, 0)

C:\Users\KimoStore\AppData\Local\Temp\ipykernel_4476\1994101410.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [80]:
cleaned_df['claime_dresp'].unique()

array([nan,  0.,  1., -9.])

In [81]:
cleaned_df[cleaned_df['claime_dresp']<0].shape[0]

1474

In [82]:
cleaned_df['claime_dresp'] = cleaned_df['claime_dresp'].replace(-9, 0)

C:\Users\KimoStore\AppData\Local\Temp\ipykernel_4476\2331088095.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [83]:
cleaned_df['property'].unique()

array([ 0,  1, -9])

In [84]:
cleaned_df[cleaned_df['property']<0].shape[0]

21386

In [85]:
cleaned_df['property'] = cleaned_df['property'].replace(-9, 0)

C:\Users\KimoStore\AppData\Local\Temp\ipykernel_4476\397317325.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [86]:
cleaned_df['ishostkid'].unique()

array([ 0.,  1., nan, -9.])

In [87]:
cleaned_df[cleaned_df['ishostkid']<0].shape[0]

317

In [88]:
cleaned_df['ishostkid'] = cleaned_df['ishostkid'].replace(-9, 0)

C:\Users\KimoStore\AppData\Local\Temp\ipykernel_4476\2338461166.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [89]:
cleaned_df['ransom_demanded'].unique()

array([ 0.,  1., nan, -9.])

In [90]:
cleaned_df[cleaned_df['ransom_demanded']<0].shape[0]

1398

In [91]:
cleaned_df['ransom_demanded'] = cleaned_df['ransom_demanded'].replace(-9, 0)

C:\Users\KimoStore\AppData\Local\Temp\ipykernel_4476\996732936.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [92]:
cleaned_df['INT_LOG'].unique()

array([ 0, -9,  1])

In [93]:
cleaned_df[cleaned_df['INT_LOG']<0].shape[0]

92527

In [94]:
cleaned_df['INT_LOG'] = cleaned_df['INT_LOG'].replace(-9, 0)

C:\Users\KimoStore\AppData\Local\Temp\ipykernel_4476\1905918708.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [95]:
cleaned_df['INT_IDEO'].unique()

array([ 0,  1, -9])

In [96]:
cleaned_df[cleaned_df['INT_IDEO']<0].shape[0]

92659

In [97]:
cleaned_df['INT_IDEO'] = cleaned_df['INT_IDEO'].replace(-9, 0)

C:\Users\KimoStore\AppData\Local\Temp\ipykernel_4476\1371546518.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [98]:
cleaned_df['INT_MISC'].unique()

array([ 0,  1, -9])

In [99]:
cleaned_df[cleaned_df['INT_MISC']<0].shape[0]

487

In [100]:
cleaned_df['INT_MISC'] = cleaned_df['INT_MISC'].replace(-9, 0)

C:\Users\KimoStore\AppData\Local\Temp\ipykernel_4476\705664011.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [101]:
cleaned_df['INT_ANY'].unique()

array([ 0,  1, -9])

In [102]:
cleaned_df[cleaned_df['INT_ANY']<0].shape[0]

83830

In [103]:
cleaned_df['INT_ANY'] = cleaned_df['INT_ANY'].replace(-9, 0)

C:\Users\KimoStore\AppData\Local\Temp\ipykernel_4476\3655267980.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



validate cateogrical data 

In [104]:
print(cleaned_df['country'].nunique())
print(cleaned_df['country'].str.lower().str.strip().nunique())

205
205


In [105]:
cleaned_df['region'].unique()

array(['Central America & Caribbean', 'North America', 'Southeast Asia',
       'Western Europe', 'East Asia', 'South America', 'Eastern Europe',
       'Sub-Saharan Africa', 'Middle East & North Africa',
       'Australasia & Oceania', 'South Asia', 'Central Asia'],
      dtype=object)

In [106]:
cleaned_df['attack_type'].unique()

array(['Assassination', 'Hostage Taking (Kidnapping)',
       'Bombing/Explosion', 'Facility/Infrastructure Attack',
       'Armed Assault', 'Hijacking', 'Unknown', 'Unarmed Assault',
       'Hostage Taking (Barricade Incident)'], dtype=object)

In [119]:
#saved clean data to csv file 
cleaned_df.to_csv('cleandata.csv')

***2- Data Analysis:***

**1- Perform basic statistical analysis using Numpy to summarize the data**

a- Calculate the mean, median, and standard deviation of relevant numeric columns

In [107]:
numeric_columns = [
    'extended', 'latitude', 'longitude', 'specificity', 'vicinity',
    'doubtterr', 'multiple', 'nperps', 'nperpcap', 'claime_dresp',
    'targsubtype1', 'natlty1', 'guncertain1', 'num_killed', 'nkillus',
    'num_terrorist_killed', 'num_wounded', 'nwoundus', 'num_terrorist_wounded',
    'propextent', 'ishostkid', 'ransom_demanded'
]

stats = {}
for col in numeric_columns:
    stats[col] = {
        'mean': np.mean(cleaned_df[col].dropna()),
        'median': np.median(cleaned_df[col].dropna()),
        'std_dev': np.std(cleaned_df[col].dropna())
    }

stats_df = pd.DataFrame(stats)
stats_df.head()


extended   latitude      longitude  specificity  vicinity  doubtterr  \
mean     0.045346  23.498343    -458.695653     1.451452  0.070031   0.159618   
median   0.000000  31.467463      43.246506     1.000000  0.000000   0.000000   
std_dev  0.208062  18.569190  204778.410576     0.995427  0.255199   0.366251   

         multiple      nperps   nperpcap  claime_dresp  targsubtype1  \
mean     0.137773  -65.360992  -1.517406      0.164453     46.971474   
median   0.000000  -99.000000   0.000000      0.000000     35.000000   
std_dev  0.344662  216.535700  12.830215      0.370686     30.953267   

            natlty1  guncertain1  num_killed   nkillus  num_terrorist_killed  \
mean     127.686441      0.08144    2.403272  0.045981              0.508058   
median   101.000000      0.00000    0.000000  0.000000              0.000000   
std_dev   89.298872      0.27351   11.545707  5.681830              4.199919   

         num_wounded  nwoundus  num_terrorist_wounded  propextent  ishostkid  \
mean        3.167668  0.038944               0.107163    3.295403   0.074772   
median      0.000000  0.000000               0.000000    3.000000   0.000000   
std_dev    35.949283  3.057348               1.488875    0.486908   0.263022   

         ransom_demanded  
mean            0.016787  
median          0.000000  
std_dev         0.128473

b- Identify the most frequent values in categorical columns.

In [108]:
def get_most_frequent(values):
    values = np.array(values)
    unique, counts = np.unique(values, return_counts=True)
    max_count_index = np.argmax(counts)
    return unique[max_count_index]

categorical_columns = [
    'country', 'region', 'provstate', 'city', 'attack_type', 'target_type',
    'target_subtype', 'corp1', 'target1', 'nationality_of_victom',
    'organisation', 'motive', 'weaptype1', 'weapon_type', 'weapsubtype1_txt',
    'weapdetail', 'propextent_desc', 'propcomment', 'scite1', 'scite2','dbsource'
]


frequent_values = {}
for col in categorical_columns:
    frequent_values[col] = get_most_frequent(cleaned_df[col].dropna()) 

frequent_values_df = pd.DataFrame(frequent_values, index=['Most Frequent'])
frequent_values_df.head()


country                      region provstate     city  \
Most Frequent    Iraq  Middle East & North Africa   Baghdad  Unknown   

                     attack_type                  target_type  \
Most Frequent  Bombing/Explosion  Private Citizens & Property   

                             target_subtype    corp1    target1  \
Most Frequent  Unnamed Civilian/Unspecified  Unknown  Civilians   

              nationality_of_victom organisation   motive  weaptype1  \
Most Frequent                  Iraq      Unknown  Unknown          6   

              weapon_type        weapsubtype1_txt weapdetail  \
Most Frequent  Explosives  Unknown Explosive Type  Explosive   

                           propextent_desc  \
Most Frequent  Minor (likely < $1 million)   

                                                     propcomment  \
Most Frequent  It is unknown if any property was damaged in t...   

                                                          scite1  \
Most Frequent  Committee on Government Operations United Stat...   

                                                          scite2  \
Most Frequent  Christopher Hewitt, "Political Violence and Te...   

                               dbsource  
Most Frequent  START Primary Collection

**2- Use Pandas to:**

a- Group data by various categories (e.g., year, region, attack type) and calculate aggregate statistics.

In [109]:
attacks_per_year = cleaned_df.groupby('year').size().reset_index(name='num_attacks').sort_values(by='num_attacks',ascending=False)
attacks_per_year


year  num_attacks
43  2014        16903
44  2015        14965
45  2016        13587
42  2013        12036
46  2017        10900
41  2012         8522
40  2011         5076
22  1992         5071
39  2010         4826
37  2008         4805
38  2009         4721
21  1991         4683
19  1989         4324
20  1990         3887
18  1988         3721
14  1984         3495
23  1994         3456
36  2007         3242
26  1997         3197
17  1987         3183
24  1995         3081
25  1996         3058
15  1985         2915
13  1983         2870
16  1986         2860
35  2006         2758
10  1980         2662
9   1979         2662
11  1981         2586
12  1982         2544
34  2005         2017
30  2001         1906
29  2000         1814
8   1978         1526
28  1999         1395
31  2002         1333
7   1977         1319
32  2003         1278
33  2004         1166
27  1998          934
6   1976          923
5   1975          740
0   1970          651
4   1974          581
2   1972          568
3   1973          473
1   1971          471

In [110]:
attacks_per_country = cleaned_df.groupby('country').size().reset_index(name='num_attacks').sort_values(by='num_attacks',ascending=False)
attacks_per_country.head(20)

country  num_attacks
84             Iraq        24636
134        Pakistan        14368
0       Afghanistan        12731
80            India        11960
35         Colombia         8306
140     Philippines         6908
139            Peru         6096
52      El Salvador         5320
188  United Kingdom         5235
183          Turkey         4292
159         Somalia         4142
130         Nigeria         3907
179        Thailand         3849
200           Yemen         3347
166           Spain         3249
167       Sri Lanka         3022
189   United States         2836
2           Algeria         2743
60           France         2693
51            Egypt         2479

In [111]:
attacks_per_region = cleaned_df.groupby('region').size().reset_index(name='num_attacks').sort_values(by='num_attacks',ascending=False)
attacks_per_region

region  num_attacks
5    Middle East & North Africa        50474
8                    South Asia        44974
7                 South America        18978
10           Sub-Saharan Africa        17550
11               Western Europe        16639
9                Southeast Asia        12485
1   Central America & Caribbean        10344
4                Eastern Europe         5144
6                 North America         3456
3                     East Asia          802
2                  Central Asia          563
0         Australasia & Oceania          282

In [112]:
attacks_per_attack_type = cleaned_df.groupby('attack_type').size().reset_index(name='num_attacks').sort_values(by='num_attacks',ascending=False)
attacks_per_attack_type

attack_type  num_attacks
2                    Bombing/Explosion        88255
0                        Armed Assault        42669
1                        Assassination        19312
6          Hostage Taking (Kidnapping)        11158
3       Facility/Infrastructure Attack        10356
8                              Unknown         7276
7                      Unarmed Assault         1015
5  Hostage Taking (Barricade Incident)          991
4                            Hijacking          659

In [113]:
attacks_per_weapon_type = cleaned_df.groupby('weapon_type').size().reset_index(name='num_attacks').sort_values(by='num_attacks',ascending=False)
attacks_per_weapon_type

weapon_type  num_attacks
2                                          Explosives        92426
4                                            Firearms        58524
10                                            Unknown        15157
5                                          Incendiary        11135
6                                               Melee         3655
1                                            Chemical          321
9                                  Sabotage Equipment          141
11  Vehicle (not to include vehicle-borne explosiv...          136
7                                               Other          114
0                                          Biological           35
3                                        Fake Weapons           33
8                                        Radiological           14

b- Identify trends over time (e.g., number of attacks per year)

In [121]:
attacks_per_year = cleaned_df.groupby('year').size()
attacks_per_year_df = attacks_per_year.reset_index(name='num_attacks')
attacks_per_year_df

year  num_attacks
0   1970          651
1   1971          471
2   1972          568
3   1973          473
4   1974          581
5   1975          740
6   1976          923
7   1977         1319
8   1978         1526
9   1979         2662
10  1980         2662
11  1981         2586
12  1982         2544
13  1983         2870
14  1984         3495
15  1985         2915
16  1986         2860
17  1987         3183
18  1988         3721
19  1989         4324
20  1990         3887
21  1991         4683
22  1992         5071
23  1994         3456
24  1995         3081
25  1996         3058
26  1997         3197
27  1998          934
28  1999         1395
29  2000         1814
30  2001         1906
31  2002         1333
32  2003         1278
33  2004         1166
34  2005         2017
35  2006         2758
36  2007         3242
37  2008         4805
38  2009         4721
39  2010         4826
40  2011         5076
41  2012         8522
42  2013        12036
43  2014        16903
44  2015        14965
45  2016        13587
46  2017        10900

In [123]:
#here i want to know the max and the min attacks happened in which year
max_attacks_year = attacks_per_year.idxmax()
max_attacks_count = attacks_per_year.max()
print(f"Max Attacks happen in year: {max_attacks_year} with ({max_attacks_count} attacks)")
min_attacks_year = attacks_per_year.idxmin()
min_attacks_count = attacks_per_year.min()
print(f"Max Attacks happen in year: {min_attacks_year} with ({min_attacks_count} attacks)")


Max Attacks happen in year: 2014 with (16903 attacks)
Max Attacks happen in year: 1971 with (471 attacks)


In [127]:
#here i want to know the changes in year 
yearly_changes = attacks_per_year.diff().dropna()

print(yearly_changes)


year
1971    -180.0
1972      97.0
1973     -95.0
1974     108.0
1975     159.0
1976     183.0
1977     396.0
1978     207.0
1979    1136.0
1980       0.0
1981     -76.0
1982     -42.0
1983     326.0
1984     625.0
1985    -580.0
1986     -55.0
1987     323.0
1988     538.0
1989     603.0
1990    -437.0
1991     796.0
1992     388.0
1994   -1615.0
1995    -375.0
1996     -23.0
1997     139.0
1998   -2263.0
1999     461.0
2000     419.0
2001      92.0
2002    -573.0
2003     -55.0
2004    -112.0
2005     851.0
2006     741.0
2007     484.0
2008    1563.0
2009     -84.0
2010     105.0
2011     250.0
2012    3446.0
2013    3514.0
2014    4867.0
2015   -1938.0
2016   -1378.0
2017   -2687.0
dtype: float64


c- Determine the most affected regions and countries

In [141]:
attacks_by_region = cleaned_df.groupby('region').size().sort_values(ascending=False).reset_index(name='num_attacks')
attacks_by_region.head(10)

region  num_attacks
0   Middle East & North Africa        50474
1                   South Asia        44974
2                South America        18978
3           Sub-Saharan Africa        17550
4               Western Europe        16639
5               Southeast Asia        12485
6  Central America & Caribbean        10344
7               Eastern Europe         5144
8                North America         3456
9                    East Asia          802

In [140]:
attacks_by_country = cleaned_df.groupby('country').size().sort_values(ascending=False).reset_index(name='num_attacks')
attacks_by_country.head(10)

country  num_attacks
0            Iraq        24636
1        Pakistan        14368
2     Afghanistan        12731
3           India        11960
4        Colombia         8306
5     Philippines         6908
6            Peru         6096
7     El Salvador         5320
8  United Kingdom         5235
9          Turkey         4292

d- Identify the most common attack types and targets

In [138]:
common_attack_types = cleaned_df.groupby('attack_type').size().sort_values(ascending=False).reset_index(name='num_attacks')
common_attack_types.head(10) 

attack_type  num_attacks
0                    Bombing/Explosion        88255
1                        Armed Assault        42669
2                        Assassination        19312
3          Hostage Taking (Kidnapping)        11158
4       Facility/Infrastructure Attack        10356
5                              Unknown         7276
6                      Unarmed Assault         1015
7  Hostage Taking (Barricade Incident)          991
8                            Hijacking          659

In [139]:
common_attack_types = cleaned_df.groupby('target_type').size().sort_values(ascending=False).reset_index(name='num_attacks')
common_attack_types.head(10) 

target_type  num_attacks
0     Private Citizens & Property        43511
1                        Military        27984
2                          Police        24506
3            Government (General)        21283
4                        Business        20669
5                  Transportation         6799
6                       Utilities         6023
7                         Unknown         5898
8  Religious Figures/Institutions         4440
9         Educational Institution         4322